ALTER TABLE aircraft
    DROP CONSTRAINT aircraft_engine_id_fkey;

CREATE TABLE engine_type
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    manufacturer VARCHAR(255),
    volume       DOUBLE PRECISION                        NOT NULL,
    fuel_type    VARCHAR(255),
    CONSTRAINT pk_enginetype PRIMARY KEY (id)
);

ALTER TABLE engine
    ADD engine_type_id BIGINT;

ALTER TABLE engine
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE engine
    ADD serial_number VARCHAR(255);

ALTER TABLE aircraft
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE engine
    ADD CONSTRAINT FK_ENGINE_ON_ENGINE_TYPE FOREIGN KEY (engine_type_id) REFERENCES engine_type (id);

ALTER TABLE aircraft
    DROP COLUMN aircraft_id;

ALTER TABLE aircraft
    DROP COLUMN engine_id;

ALTER TABLE engine
    DROP COLUMN engine_id;

ALTER TABLE engine
    DROP COLUMN fuel_type;

ALTER TABLE engine
    DROP COLUMN manufacturer;

ALTER TABLE engine
    DROP COLUMN volume;

ALTER TABLE aircraft
    ALTER COLUMN airframe DROP NOT NULL;

ALTER TABLE aircraft
    ALTER COLUMN pilot DROP NOT NULL;

ALTER TABLE aircraft
    ADD CONSTRAINT pk_aircraft PRIMARY KEY (id);

ALTER TABLE engine
    ADD CONSTRAINT pk_engine PRIMARY KEY (id);